workflows:
  build-app:
    name: Build Expo Android App
    environment:
      node: latest
    scripts:
      - npm install
      - npx expo install
      - npx expo export
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - hamidr984@gmail.com
