workflows:
  android-build:
    name: Build Expo Android App
    environment:
      node: latest
    scripts:
      - npm install
      - npx expo install
      - npx expo prebuild
      - npx expo build:android -t apk
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hamidr984@gmail.com
