workflows:
  android-build:
    name: Build Expo Android App (EAS)
    environment:
      node: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN   # اینجا توکن Expo رو به محیط اضافه می‌کنیم
    scripts:
      - npm install
      - npx expo install
      - npx expo prebuild --platform android
      - npx eas-cli build -p android --profile preview
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hamidr984@gmail.com
