workflows:
  android-build:
    name: Build Expo Android App (EAS)
    environment:
      node: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # توکن Expo از Codemagic Environment
    scripts:
      - npm install
      - npx expo install
      - npx expo prebuild --platform android
      - npx eas-cli build --platform android --profile production --non-interactive
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - hamidr984@gmail.com
